apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    tier: rc-frontend
spec:
  replicas: 3
  selector:
    name: myapp
    tier: frontend
  template:
    metadata:
     name: mypod2
     labels:
       name: myapp
       tier: frontend
    spec:
      containers:
       - image: coolgourav147/nginx-custom
         name: cont3