apiVersion: v1
kind: Pod
metadata:
  name: multicont
  labels:
    name: myapp
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: cont1
    image: nginx
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
  - name: cont2
    image: debian
    volumeMounts:
     - name: html
       mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done
